name: dashboard-ocr
dependencies:
  - python=3.6
  - pandas
  - pymysql
  - flask
  - openpyxl
  - pylint
  - yapf
  - numpy
  - matplotlib
  - tensorflow
  - tensorboard
  - pillow
  - tqdm
  - requests
